
$ cat config/database.yml
development:
  adapter: postgresql
  encoding: unicode
  database: my-digital
  pool: 5
  username: root
  password: root
  host: localhost
$ echo $DATABASE_URL

production:
  adapter: postgresql
  encoding: unicode
  database: my-digitalca
  pool: 5
  username: root
  password: root
  host: localhost
